pipeline {
   agent any
   stages {
      stage('PrintGeopolitica') {
         steps {
			  script{
				println "Informacion geopolitica de España: Provincias y sus capitales\n\nProvincia: A Coruña\t\t-\t\tCapital: A Coruña\nProvincia: Alacant\t\t-\t\tCapital: Alacant\nProvincia: Albacete\t\t-\t\tCapital: Albacete\nProvincia: Almería\t\t-\t\tCapital: Almería\nProvincia: Araba\t\t-\t\tCapital: Araba\nProvincia: Asturias\t\t-\t\tCapital: Asturias\nProvincia: Badajoz\t\t-\t\tCapital: Badajoz\nProvincia: Barcelona\t\t-\t\tCapital: Barcelona\nProvincia: Bizkaia\t\t-\t\tCapital: Bizkaia\nProvincia: Burgos\t\t-\t\tCapital: Burgos\nProvincia: Cantabria\t\t-\t\tCapital: Cantabria\nProvincia: Castelló\t\t-\t\tCapital: Castelló\nProvincia: Ceuta\t\t-\t\tCapital: Ceuta\nProvincia: Ciudad Real\t\t-\t\tCapital: Ciudad Real\nProvincia: Cuenca\t\t-\t\tCapital: Cuenca\nProvincia: Cáceres\t\t-\t\tCapital: Cáceres\nProvincia: Cádiz\t\t-\t\tCapital: Cádiz\nProvincia: Córdoba\t\t-\t\tCapital: Córdoba\nProvincia: Gipuzcoa\t\t-\t\tCapital: Gipuzcoa\nProvincia: Girona\t\t-\t\tCapital: Girona\nProvincia: Granada\t\t-\t\tCapital: Granada\nProvincia: Guadalajara\t\t-\t\tCapital: Guadalajara\nProvincia: Huelva\t\t-\t\tCapital: Huelva\nProvincia: Huesca\t\t-\t\tCapital: Huesca\nProvincia: Illes Balears\t\t-\t\tCapital: Illes Balears\nProvincia: Jaén\t\t-\t\tCapital: Jaén\nProvincia: La Rioja\t\t-\t\tCapital: La Rioja\nProvincia: Las Palmas\t\t-\t\tCapital: Las Palmas\nProvincia: León\t\t-\t\tCapital: León\nProvincia: Lleida\t\t-\t\tCapital: Lleida\nProvincia: Lugo\t\t-\t\tCapital: Lugo\nProvincia: Madrid\t\t-\t\tCapital: Madrid\nProvincia: Melilla\t\t-\t\tCapital: Melilla\nProvincia: Murcia\t\t-\t\tCapital: Murcia\nProvincia: Málaga\t\t-\t\tCapital: Málaga\nProvincia: Navarra\t\t-\t\tCapital: Navarra\nProvincia: Ourense\t\t-\t\tCapital: Ourense\nProvincia: Palencia\t\t-\t\tCapital: Palencia\nProvincia: Pontevedra\t\t-\t\tCapital: Pontevedra\nProvincia: Salamanca\t\t-\t\tCapital: Salamanca\nProvincia: Santa Cruz de Tenerife\t\t-\t\tCapital: Santa Cruz de Tenerife\nProvincia: Segovia\t\t-\t\tCapital: Segovia\nProvincia: Sevilla\t\t-\t\tCapital: Sevilla\nProvincia: Soria\t\t-\t\tCapital: Soria\nProvincia: Tarragona\t\t-\t\tCapital: Tarragona\nProvincia: Teruel\t\t-\t\tCapital: Teruel\nProvincia: Toledo\t\t-\t\tCapital: Toledo\nProvincia: Valladolid\t\t-\t\tCapital: Valladolid\nProvincia: València\t\t-\t\tCapital: València\nProvincia: Zamora\t\t-\t\tCapital: Zamora\nProvincia: Zaragoza\t\t-\t\tCapital: Zaragoza\nProvincia: Ávila\t\t-\t\tCapital: Ávila\n\nInformacion obtenida para el usuario Eduardo López con ID 2857 el 12/09/2022"
			  }
         }
      }
   }
}

